### ISSUE TITLE
Prompted to provide --cluster-name & --region flag

### ISSUE THREAD

**Issue by rothgar** [surajincloud/kubectl-eks#45] opened 2023-06-08 18:15 UTC
Sometimes when I'm running the plugin it errors and tells me to provide the cluster name. I haven't figured out why (yet). Usually I have an exported KUBECONFIG file with a single cluster but providing the --cluster-name doesn't resolve the issue.

Here's an example. You can see that `k get nodes` works fine but `k eks nodes` doesn't know what cluster to use. My KUBECONFIG var is set to `/home/ANT.AMAZON.COM/rothgar/.kube/spot`

```
☸ spot in .dotfiles on  main [$] on ☁️  demo (us-east-1) 
❯ k config get-clusters
NAME
arn:aws:eks:us-east-1:323238900174:cluster/spot

☸ spot in .dotfiles on  main [$] on ☁️  demo (us-east-1) 
❯ k get no | head -3
NAME                              STATUS   ROLES    AGE   VERSION
ip-192-168-100-26.ec2.internal    Ready    <none>   19h   v1.27.1-eks-2f008fe
ip-192-168-101-104.ec2.internal   Ready    <none>   18h   v1.27.1-eks-2f008fe

☸ spot in .dotfiles on  main [$] on ☁️  demo (us-east-1) 
❯ k eks nodes
2023/06/08 11:12:56 please pass cluster name with --cluster-name or with AWS_EKS_CLUSTER environment variable

☸ spot in .dotfiles on  main [$] on ☁️  demo (us-east-1) 
❯ k eks nodes --cluster-name spot
Error: unknown flag: --cluster-name
Usage:
  kubectl-eks nodes [flags]

Flags:
  -h, --help   help for nodes

Global Flags:
      --as string                      Username to impersonate for the operation. User could be a regular user or a service account in a namespace.
...
```

**Comment by surajnarwade** [comment] 2023-06-08 18:38
ah I think I know why this is happening, there's no `--cluster-name` flag defined  for `nodes` command like how it is for other commands https://github.com/surajincloud/kubectl-eks/blob/main/cmd/nodegroups.go#L86

will get it fixed quickly

**Comment by surajnarwade** [comment] 2023-06-08 18:47
I think, #46 just fixes the flag problem, but I will check other issues as well.

**Comment by rothgar** [comment] 2023-06-08 20:28
I just built main `4b87943` and still get prompted for cluster name

**Comment by surajnarwade** [comment] 2023-06-08 21:11
@rothgar this should fix the issue: https://github.com/surajincloud/kubectl-eks/pull/47 try the `main` now.

This line was the culprit: https://github.com/surajincloud/kubectl-eks/pull/47/files#diff-b1ddc12073437afb094f910de081ff3d1fa4a61572ddb44409a9e82b0e975b19L39 which was asking for `--cluster-name``

should be fixed now

**Comment by rothgar** [comment] 2023-06-09 17:03
Yep, that works.

There is a semi-related issue I have where the plugin explicitly requires AWS_REGION to be set in the environment instead of using my default configured in the AWS profile. You can see here in the command output. Notice my terminal prompt (using [starship.rs](https://starship.rs)) picks up my default region configured from the profile

```
☸ production in demos/clearwater on  main [$✘!?] on ☁️  demo (us-west-2)                                                                                                                                           
❯ /home/ANT.AMAZON.COM/rothgar/src/kubectl-eks/kubectl-eks nodes                                                                                                                                                   
2023/06/09 09:58:15 please pass region name with --region or with AWS_REGION environment variable                                                                                                                  
                                                                                                                                                                                                                   
☸ production in demos/clearwater on  main [$✘!?] on ☁️  demo (us-west-2)                                                                                                                                           
❯ env | grep AWS_                                                                                                                                                                                                            
AWS_PROFILE=demo                                                                                                                                                                                                   
AWS_DEFAULT_PROFILE=demo                                                                                                                                                                                           
                                                                                                                                                                                                                   
☸ production in demos/clearwater on  main [$✘!?] on ☁️  demo (us-west-2)                                                                                                                                           
❯ export AWS_REGION=us-west-2
                                                                                                                                                                                                                   
☸ production in demos/clearwater on  main [$✘!?] on ☁️  demo (us-west-2)                                                                                                                                           
❯ /home/ANT.AMAZON.COM/rothgar/src/kubectl-eks/kubectl-eks nodes                                                                                                                                                   
NAME                                              INSTANCE-TYPE
```

**Comment by surajnarwade** [comment] 2023-06-09 21:10
@rothgar that's great point, I kind of know why that's happening, fix is coming in #48 Happy Friyay :tada:

**Comment by surajnarwade** [comment] 2023-06-09 21:13
@rothgar try the `main` now? should work as intended. I changed the issue name for tracking both the flags :)

**Comment by rothgar** [comment] 2023-06-13 23:23
This worked for me. :+1:

**Comment by surajnarwade** [comment] 2023-06-14 04:42
closing this as it is fixed in: https://github.com/surajincloud/kubectl-eks/releases/tag/v0.3.0

**Closed by surajnarwade** 2023-06-14 04:42 UTC
